clear;
clc;

%% initialize
bidspmDir=fullfile(fileparts(mfilename('fullpath')),'..', 'lib','bidspm');
addpath(fullfile(fileparts(mfilename('fullpath')),'..', 'lib','bidspm'))
bidspm();

%% set paths
%changed it to absolute because there were erros.bids_dir = fullfile(fileparts(mfilename('fullpath')),'..', '..','inputs','raw');
bids_dir  ='/Users/shahzad/Files/fMRI/SenseSmell/inputs/raw';

%changed it to absolute because there were erros.output_dir = fullfile(fileparts(mfilename('fullpath')),'..', '..','outputs','derivatives');
output_dir = '/Users/shahzad/Files/fMRI/SenseSmell/outputs';

%preproc_dir = fullfile(fileparts(mfilename('fullpath')),'..', '..','outputs','derivatives','bidspm-preproc');
preproc_dir = '/Users/shahzad/Files/fMRI/SenseSmell/outputs/derivatives/bidspm-preproc';

%for mvpa
model_file = '/Users/shahzad/Files/fMRI/SenseSmell/code/model/model-olfa_mvpa_smdl.json';

%% preprocess = STC, spatial normalization and smooth FWHM = 0
% bidspm(bids_dir, output_dir, 'subject', ...
%     'action', 'preprocess', ...
%     'participant_label', {'001'}, ...
%     'space', {'IXI549Space'}, ...
%     'fwhm', 0, ...
%     'task', 'olfa');

%% preprocess = STC, spatial normalization and smooth FWHM = 2
bidspm(bids_dir, output_dir, 'subject', ...
    'action', 'preprocess', ...
    'participant_label', {'001'}, ...
    'space', {'IXI549Space'}, ...
    'fwhm', 2, ...
    'task', 'olfa');

%% GLM to do MVPA 

% taskName = 'olfa';
% bidspm(bids_dir, output_dir, 'subject', ...
%        'participant_label', {'001'}, ...    
%        'action', 'stats', ...
%        'preproc_dir', preproc_dir, ...
%        'model_file', model_file,...
%        'task', {taskName},...
%        'space', {'IXI549Space'}, ...
%        'fwhm', 0,...
%        'ignore', {'qa','concat'},...
%        'concatenate', true);

taskName = 'olfa';
bidspm(bids_dir, output_dir, 'subject', ...
       'participant_label', {'001'}, ...    
       'action', 'stats', ...
       'preproc_dir', preproc_dir, ...
       'model_file', model_file,...
       'task', {taskName},...
       'space', {'IXI549Space'}, ...
       'fwhm', 2,...
       'ignore', {'qa','concat'},...
       'concatenate', true);